config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :categories
    resources :questions
    resources :courses
    root 'static_pages#index'
    get 'static_pages/index'
  end
  get 'exam/show'
  resources :courses do
    resources :exams
  end

  devise_for :users,
  path: '',
  path_names: {sign_in: 'login' ,sign_out: 'logout' ,edit: 'profile',sign_up: 'resgistration'},
  controllers: {omniauth_callbacks: 'omniauth_callbacks' }
  # controllers:{omniauth_callbacks: "users/omniauth_callbacks"}
  root 'static_pages#index'

  as :user do
    get "signin" => "devise/sessions#new"
    post "signin" => "devise/sessions#create"
    delete "signout" => "devise/sessions#destroy"
  end


  resources :categories  

  resources :categories
  resources :courses
  resources :exams

  resources :examanswers
  resources :results

  
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    if user.present?  # additional permissions for logged in users (they can see their own exams)
      can :read, Exam, user_id: user.id

      if user.admin?  # additional permissions for administrators
        can :manage, :all
      end
    end
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
	has_many :results
	has_many :exams, through: :results
	belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :courses
	validates :category_name, presence: true
end

app/models/course.rb
class Course < ApplicationRecord
	searchkick
	has_many :exams
	has_many :users, through: :exams
	has_many :objectives
	belongs_to :category
	has_many :questions
	validates :course_name, presence: true
end

app/models/exam.rb
class Exam < ApplicationRecord
	belongs_to :user
	belongs_to :course
	has_many :results


	has_many :questions, through: :results
	has_many :answers, through: :results

	accepts_nested_attributes_for :results
end

app/models/exam_answer.rb
class ExamAnswer < ApplicationRecord
	belongs_to :exam
	belongs_to :answer
end

app/models/exam_question.rb
class ExamQuestion < ApplicationRecord
	belongs_to :exam
	belongs_to :question
end

app/models/objective.rb
class Objective < ApplicationRecord
    belongs_to :course
end

app/models/question.rb
class Question < ApplicationRecord
	searchkick
	has_many :results
	has_many :exams, through: :results
	has_many :answers, dependent: :destroy
	belongs_to :course
	validates :question_name, presence: true
	delegate :course_name, to: :course, prefix: :co, allow_nil: true
	accepts_nested_attributes_for :answers,
	reject_if: proc {|attribute| attribute[:answer_content].blank?}
end

app/models/result.rb
class Result < ApplicationRecord
	belongs_to :exam
	belongs_to :question
	belongs_to :answer, optional: true
	delegate :is_correct, to: :answer, prefix: :answer, allow_nil: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :exams
  has_many :courses, through: :exams
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable,
  :omniauthable , omniauth_providers: [:facebook, :google_oauth2]

  def self.from_omniauth(auth)
  	result = User.where(email: auth.info.email).first
  	if result
  		return result
  	else
  		where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
  			user.email = auth.info.email
  			user.password = Devise.friendly_token[0,20]
  			user.fullname = auth.info.name
  			user.image = auth.info.image
  			user.uid = auth.uid
  			user.provider = auth.provider

        #  If you are using confirmable and the provider(s) you use validate emails
        user.skip_confirmation!
      end
    end
  end
end

app/models/user_course.rb
class UserCourse < ApplicationRecord
	belongs_to :course
	belongs_to :user
end

app/controllers/admin/questions_controller.rb
class Admin::QuestionsController < Admin::AdminController
  before_action :set_question, only: %i[ show edit update destroy ]

  def index
    if params[:question].present?
      Question.reindex
      @questions = Question.search params[:question]
    else
      @pagy, @questions = pagy(Question.all, items: 10)
    end
  end

  def new
    @question = Question.new
    @question.answers.build
    @question.answers.build
    @question.answers.build
    @question.answers.build
  end

  def create
    @question = Question.new(question_params)
    if @question.save
      redirect_to admin_questions_path
      flash[:success] = "Question was successfully created."
    else
      redirect_to admin_questions_path
      flash[:danger] = 'Error' 
    end
  end

  def show
    
  end

  def edit

  end

  def update
    @question.update(question_params)
    flash[:success] = "Question updated"
    redirect_to admin_questions_path
  end

  def destroy
    @question.destroy
    flash[:success] = 'Question deleted'
    redirect_to admin_questions_path
  end

  private
    def set_question
      @question = Question.find(params[:id])
    end

    def question_params
      params.require(:question).permit(:question_name, :course_id, answers_attributes: [:id, :answer_content, :is_correct]);
    end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
	before_action :authenticate_user!
end

app/helpers/admin/questions_helper.rb
module Admin::QuestionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
    include Pagy::Frontend
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/course_helper.rb
module CourseHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/exam_helper.rb
module ExamHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/admin/questions/_form.html.erb
<div class="pb-2 mb-3 border-bottom">
    <h1 class="h2">New Question</h1>
</div>
<%= form_with(model: [:admin, @question]) do |form| %>
<div class="form-group">
    <label for="question_name">Question</label>
    <%= form.text_field (:question_name), class: "form-control", id: "question_name", placeholder: "Question name" %>
</div>
<div class="form-group">
    <%= collection_select(:question, :course_id, Course.all, :id, :course_name, {prompt: "Select course"}, {class: "form-control course-select"}) %>
</div>
<%= field_set_tag 'Questions', class: "form-group" do %>
<span>Please fill out the answer & select which one is corrected.</span>
<%= form.fields_for :answers do |answer| %>
<div class="row pt-1 pb-1">
    <div class="col-auto">
        <div class="form-check">
            <%= answer.check_box :is_correct, class: "form-check-input"%>
        </div>
    </div>
    <div class="col-8">
        <%= answer.text_field :answer_content, class: "form-control" %>
    </div>
</div>
<% end %>
<% end %>
<%= link_to "Cancel", admin_questions_path, class: "btn btn-secondary btn-sm" %>
<%= form.submit class: "btn btn-primary btn-sm"%>
<% end %>
<%= javascript_pack_tag "checkbox" %>

app/views/admin/questions/edit.html.erb
<% provide(:title, "Edit Question") %>
<div class="container">
    <%= render 'form', admin: @question %>
</div>

app/views/admin/questions/index.html.erb
<% provide(:title, "Question manage") %>

<div class="pb-2 mb-3 border-bottom">
    <h1 class="h2">Question</h1>
</div>
<div class="d-flex flex-column justify-center mt-4">
    <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <form action="/admin/questions">
        <div class="form-row mb-2">
            <div class="col-auto">
                <%= text_field_tag (:question), "", placeholder: "Search Question", class: "form-control" %>
            </div>
            <button class="btn btn-primary btn-sm" type="submit">Search</button>
        </div>
    </form>
    <span>
        <%= params[:question].present? && @questions.any? ? "Display result with '#{params[:question]}':"  : '' %>
    </span>
    <table class="table">
        <thead class="thead-dark">
            <tr>
                <th scope="col">ID</th>
                <th scope="col">Question</th>
                <th scope="col">Course</th>
                <th scope="col">Created at</th>
                <th scope="col">
                    <!-- Button trigger modal -->
                    <%= link_to "Add new", new_admin_question_path, class: "btn btn-primary btn-sm" %>
                    <%= link_to "Reset", admin_questions_path, class: "btn btn-primary btn-sm"%>
                </th>
            </tr>
        </thead>
        <tbody class="listQuestion">
            <% if @questions.any?%>
                <% @questions.each do |c| %>
                <tr>
                    <th scope="row"><%= c.id %></th>
                    <td><%= c.question_name %></td>
                    <td><%= c.co_course_name %></td>
                    <td><%= c.created_at %></td>
                    <td>
                        <%= link_to "Edit", edit_admin_question_path(c), class: "btn btn-primary btn-sm" %>
                        <%= link_to "Delete", admin_question_path(c), method: :delete, data: {confirm: "You sure?"}, class: "btn btn-danger btn-sm" %>
                    </td>
                </tr>
                <% end %>
            <% else %>
                <span>Không có câu hỏi nào</span>
            <% end %>
        </tbody>
    </table>
    <% if @pagy.present?%>
        <%== pagy_bootstrap_nav(@pagy) %>
    <% end %>
</div>

app/views/admin/questions/new.html.erb
<% provide(:title, "New Question") %>
<div class="container">
    <%= render 'form', admin: @question %>
</div>

app/views/admin/questions/show.html.erb
<h1>Admin::Questions#show</h1>
<p>Find me in app/views/admin/questions/show.html.erb</p>