config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :categories
    resources :questions
    resources :courses
    root 'static_pages#index'
    get 'static_pages/index'
  end
  get 'exam/show'
  resources :courses do
    resources :exams
  end

  devise_for :users,
  path: '',
  path_names: {sign_in: 'login' ,sign_out: 'logout' ,edit: 'profile',sign_up: 'resgistration'},
  controllers: {omniauth_callbacks: 'omniauth_callbacks' }
  # controllers:{omniauth_callbacks: "users/omniauth_callbacks"}
  root 'static_pages#index'

  as :user do
    get "signin" => "devise/sessions#new"
    post "signin" => "devise/sessions#create"
    delete "signout" => "devise/sessions#destroy"
  end


  resources :categories  

  resources :categories
  resources :courses
  resources :exams

  resources :examanswers
  resources :results

  
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    if user.present?  # additional permissions for logged in users (they can see their own exams)
      can :read, Exam, user_id: user.id

      if user.admin?  # additional permissions for administrators
        can :manage, :all
      end
    end
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
	has_many :results
	has_many :exams, through: :results
	belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :courses
	validates :category_name, presence: true
end

app/models/course.rb
class Course < ApplicationRecord
	searchkick
	has_many :exams
	has_many :users, through: :exams
	has_many :objectives
	belongs_to :category
	has_many :questions
	validates :course_name, presence: true
end

app/models/exam.rb
class Exam < ApplicationRecord
	belongs_to :user
	belongs_to :course
	has_many :results


	has_many :questions, through: :results
	has_many :answers, through: :results

	accepts_nested_attributes_for :results
end

app/models/exam_answer.rb
class ExamAnswer < ApplicationRecord
	belongs_to :exam
	belongs_to :answer
end

app/models/exam_question.rb
class ExamQuestion < ApplicationRecord
	belongs_to :exam
	belongs_to :question
end

app/models/objective.rb
class Objective < ApplicationRecord
    belongs_to :course
end

app/models/question.rb
class Question < ApplicationRecord
	searchkick
	has_many :results
	has_many :exams, through: :results
	has_many :answers, dependent: :destroy
	belongs_to :course
	validates :question_name, presence: true
	delegate :course_name, to: :course, prefix: :co, allow_nil: true
	accepts_nested_attributes_for :answers,
	reject_if: proc {|attribute| attribute[:answer_content].blank?}
end

app/models/result.rb
class Result < ApplicationRecord
	belongs_to :exam
	belongs_to :question
	belongs_to :answer, optional: true
	delegate :is_correct, to: :answer, prefix: :answer, allow_nil: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :exams
  has_many :courses, through: :exams
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable,
  :omniauthable , omniauth_providers: [:facebook, :google_oauth2]

  def self.from_omniauth(auth)
  	result = User.where(email: auth.info.email).first
  	if result
  		return result
  	else
  		where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
  			user.email = auth.info.email
  			user.password = Devise.friendly_token[0,20]
  			user.fullname = auth.info.name
  			user.image = auth.info.image
  			user.uid = auth.uid
  			user.provider = auth.provider

        #  If you are using confirmable and the provider(s) you use validate emails
        user.skip_confirmation!
      end
    end
  end
end

app/models/user_course.rb
class UserCourse < ApplicationRecord
	belongs_to :course
	belongs_to :user
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::AdminController
  before_action :set_category, only: %i[ show edit update destroy ]

  def index    
    @categories = Category.all
    @category = Category.new
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to admin_categories_path
      notice = 'Category was successfully created.'
    else
      redirect_to admin_categories_path
      flash[:danger] = 'Error' 
    end
  end

  def show

  end

  def edit

  end

  def update
    @category.update(category_params)
    flash[:success] = "Category updated"
    redirect_to admin_categories_path
  end

  def destroy
    @category.destroy
    flash[:success] = 'Category deleted'
    redirect_to admin_categories_path
  end

  private
    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:category_name);
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	before_action :find_category, only: [:show]

	def index
		@categories = Category.all
	end

	def show
		# @courses = Course.where(category_id: params[:id])
		@categories = Category.all
		@courses = @category.courses
	end

	private
	def find_category
		@category = Category.find_by id: params[:id]
		unless @category.present?
			flash[:success] = "Category doesn't exist"
			redirect_to root_path
		end
	end

end

app/controllers/user_controller.rb
class UserController < ApplicationController
	before_action :authenticate_user!
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
    include Pagy::Frontend
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/course_helper.rb
module CourseHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/exam_helper.rb
module ExamHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/admin/categories/_form.html.erb
<%= form_with(model: [:admin, @category]) do |form| %>
<div class="modal fade" id="newCategoryModel" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">New Category</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="form-group">
                    <label for="category_name">Category</label>
                    <%= form.text_field (:category_name), class: "form-control", id: "category_name", placeholder: "Category" %>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary btn-sm" data-dismiss="modal">Close</button>
                <%= form.submit 'Add', class: "btn btn-primary btn-sm"%>
            </div>
        </div>
    </div>
</div>
<% end %>

app/views/admin/categories/create.js.erb
dd

app/views/admin/categories/edit.html.erb
<% provide(:title, "Edit Category") %>
<div class="pb-2 mb-3 border-bottom">
    <h1 class="h2">Editing Category</h1>
</div>
<%= form_with(model: [:admin, @category]) do |form| %>
<div class="form-group">
    <label for="category_name">Category</label>
    <%= form.text_field (:category_name), class: "form-control", id: "category_name" %>
</div>
<%= form.submit 'Edit', class: "btn btn-primary btn-sm"%>
<% end %>

app/views/admin/categories/index.html.erb
<% provide(:title, "Home") %>
<div class="pb-2 mb-3 border-bottom">
    <h1 class="h2">Category</h1>
</div>
<div class="d-flex flex-column justify-center mt-4">
    <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <table class="table">
        <thead class="thead-dark">
            <tr>
                <th scope="col">ID</th>
                <th scope="col">Category</th>
                <th scope="col">Created at</th>
                <th scope="col">
                    <!-- Button trigger modal -->
                    <%= link_to "Add new", '#', class: "btn btn-primary btn-sm", data: {toggle: 'modal', target: '#newCategoryModel'} %>

                    <!-- Modal -->
                    <%= render 'form', category: @category %>
                </th>
            </tr>
        </thead>
        <tbody>
            <% @categories.each do |c| %>
            <tr>
                <th scope="row"><%= c.id %></th>
                <td><%= c.category_name %></td>
                <td><%= c.created_at %></td>
                <td>
                    <%= link_to "Edit", edit_admin_category_path(c.id), class: "btn btn-primary btn-sm" %>
                    <%= link_to "Delete", admin_category_path(c.id), method: :delete, data: {confirm: "You sure?"}, class: "btn btn-danger btn-sm" %>
                </td>
            </tr>
            <% end %>
        </tbody>
    </table>
</div>

app/views/admin/categories/new.html.erb
<h1>Admin::Categories#new</h1>
<p>Find me in app/views/admin/categories/new.html.erb</p>

app/views/admin/categories/show.html.erb
<h1>Admin::Categories#show</h1>
<p>Find me in app/views/admin/categories/show.html.erb</p>

app/views/categories/_categories.html.erb
<div class="row block-4">
	<div class="col-md-2">
		<input type="checkbox" class="ant-checkbox-input" value="Linux">
	</div>
	<div class="col-md-10 ant-checkbox-group-item">
		<span><%= @category.category_name %></span>
	</div>
</div>

app/views/categories/_category.html.erb
<div class="row block-4">
	<div class="col-md-2">
		<input type="checkbox" class="ant-checkbox-input" value="Linux">
	</div>
	<div class="col-md-10 ant-checkbox-group-item">
		<%= link_to category.category_name, category_path(category), class: "btn btn-primary" %>
	</div>
</div>

app/views/categories/index.html.erb
<section class="category-section">
	<div class="container" style="background-color: #FFF">
		<div class="row">
			<div class="col-md-2" style=" min-height: 800px">
				<div class="row block-1">
					<input icon="search" placeholder="Enter keyword..." class="ant-input" type="text" value="">
				</div>
				<div class="row" style="padding-bottom: 20px">
					<span class="ant-tag m-1 ">Linux</span>
					<span class="ant-tag m-1 ">LPIC</span>
					<span class="ant-tag m-1 ">CCNP</span>
					<span class="ant-tag m-1 ">CCNA</span>
					<span class="ant-tag m-1 ">Ruby</span>
					<span class="ant-tag m-1 ">ISTQB</span>
					<span class="ant-tag m-1 ">AWS</span>
					<span class="ant-tag m-1 ">FE</span>
					<span class="ant-tag m-1 ">Laravel</span>
					<span class="ant-tag m-1 ">Kubernetes</span>
				</div>
				<hr>
				<div class="row block-3">
					<h4>Categorites</h4>
				</div>
				<hr>
				<%= render @categories %>
				
			</div>

			<div class="col-md-10" style="background-color: #e2e8f0; min-height: 500px">

				<div>
					<div class="certificates__item mt-3 row rounded">
						<img class="col-4 p-0 rounded" src="/assets/default.png">
						<div class="body col-8 pt-2">
							<div class="title">
								<p class="cursor-pointer pt-2">
									<a href="#">Ruby advance course</a>
								</p>
							</div>
							<div class="info mt-5">
								<div class="d-flex bd-highlight">
									<div class="p-2 flex-fill bd-highlight">
										<a href="#" class="badge badge-primary">Beginning Level</a>
									</div>
									<div class="p-2 flex-fill bd-highlight">Students: 2</div>
									<div class="p-2 flex-fill bd-highlight">Created at: 19/03/2021</div>
									<div class="p-2 flex-fill bd-highlight">Views: 2</div>
								</div>
							</div>
						</div>
					</div>
				</div>

			</div>
		</div>
	</div>
</section>

app/views/categories/show.html.erb
<section class="category-section">
	<div class="container" style="background-color: #FFF">
		<div class="row">
			<div class="col-md-2" style=" min-height: 800px">
				<div class="row block-1">
					<input icon="search" placeholder="Enter keyword..." class="ant-input" type="text" value="">
				</div>
				<div class="row" style="padding-bottom: 20px">
					<span class="ant-tag m-1 ">Linux</span>
					<span class="ant-tag m-1 ">LPIC</span>
					<span class="ant-tag m-1 ">CCNP</span>
					<span class="ant-tag m-1 ">CCNA</span>
					<span class="ant-tag m-1 ">Ruby</span>
					<span class="ant-tag m-1 ">ISTQB</span>
					<span class="ant-tag m-1 ">AWS</span>
					<span class="ant-tag m-1 ">FE</span>
					<span class="ant-tag m-1 ">Laravel</span>
					<span class="ant-tag m-1 ">Kubernetes</span>
				</div>
				<hr>
				<div class="row block-3">
					<h4>Categorites</h4>
				</div>
				<hr>




				<%= render "categories" %>






			</div>

			<div class="col-md-10" style="background-color: #e2e8f0; min-height: 500px">
				<div class="row right-block">
					<div class="col-md-4" style="background-color: #a4cce6">
						<img src="/assets/css-course.jpg" style="width: 100%; position: absolute; margin: 0px">
					</div>
					<div class="col-md-8">
						<div class="row" style="min-height: 50px; background-color: white">
							<p class="cursor-pointer pt-4 pr-4">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;CSS Advanced</p>
						</div>
						<div class="row block-07" style="min-height: 100px;">
							<div class="col-md-5">
								<span class="ant-tag course-level course-level__advanced">Advanced Level</span>
							</div>
							<div class="col-md-2 mr-2-img">
								<img src="/assets/users.svg" alt="" class="mr-2">120
							</div>
							<div class="col-md-3 anticon anticon-calendar-date">
								<i aria-label="icon: calendar" class="anticon anticon-calendar"><svg viewBox="64 64 896 896" focusable="false" class="" data-icon="calendar" width="1em" height="1em" fill="currentColor" aria-hidden="true"><path d="M880 184H712v-64c0-4.4-3.6-8-8-8h-56c-4.4 0-8 3.6-8 8v64H384v-64c0-4.4-3.6-8-8-8h-56c-4.4 0-8 3.6-8 8v64H144c-17.7 0-32 14.3-32 32v664c0 17.7 14.3 32 32 32h736c17.7 0 32-14.3 32-32V216c0-17.7-14.3-32-32-32zm-40 656H184V460h656v380zM184 392V256h128v48c0 4.4 3.6 8 8 8h56c4.4 0 8-3.6 8-8v-48h256v48c0 4.4 3.6 8 8 8h56c4.4 0 8-3.6 8-8v-48h128v136H184z"></path></svg></i>
								23/3/2021
							</div>
							<div class="col-md-2 anticon-eye-number">
								<i aria-label="icon: eye" class="anticon anticon-eye"><svg viewBox="64 64 896 896" focusable="false" class="" data-icon="eye" width="1em" height="1em" fill="currentColor" aria-hidden="true"><path d="M942.2 486.2C847.4 286.5 704.1 186 512 186c-192.2 0-335.4 100.5-430.2 300.3a60.3 60.3 0 0 0 0 51.5C176.6 737.5 319.9 838 512 838c192.2 0 335.4-100.5 430.2-300.3 7.7-16.2 7.7-35 0-51.5zM512 766c-161.3 0-279.4-81.8-362.7-254C232.6 339.8 350.7 258 512 258c161.3 0 279.4 81.8 362.7 254C791.5 684.2 673.4 766 512 766zm-4-430c-97.2 0-176 78.8-176 176s78.8 176 176 176 176-78.8 176-176-78.8-176-176-176zm0 288c-61.9 0-112-50.1-112-112s50.1-112 112-112 112 50.1 112 112-50.1 112-112 112z"></path></svg></i>564
							</div>
						</div>
					</div>
				</div>
				<div class="row right-block">
					<div class="col-md-4" style="background-color: #a4cce6">
						<img src="/assets/css-course.jpg" style="width: 100%; position: absolute; margin: 0px">
					</div>
					<div class="col-md-8">
						<div class="row" style="min-height: 50px; background-color: white">
							<p class="cursor-pointer pt-4 pr-4">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;CSS Advanced</p>
						</div>
						<div class="row block-07" style="min-height: 100px;">
							<div class="col-md-5">
								<span class="ant-tag course-level course-level__advanced">Advanced Level</span>
							</div>
							<div class="col-md-2 mr-2-img">
								<img src="/assets/users.svg" alt="" class="mr-2">120
							</div>
							<div class="col-md-3 anticon anticon-calendar-date">
								<i aria-label="icon: calendar" class="anticon anticon-calendar"><svg viewBox="64 64 896 896" focusable="false" class="" data-icon="calendar" width="1em" height="1em" fill="currentColor" aria-hidden="true"><path d="M880 184H712v-64c0-4.4-3.6-8-8-8h-56c-4.4 0-8 3.6-8 8v64H384v-64c0-4.4-3.6-8-8-8h-56c-4.4 0-8 3.6-8 8v64H144c-17.7 0-32 14.3-32 32v664c0 17.7 14.3 32 32 32h736c17.7 0 32-14.3 32-32V216c0-17.7-14.3-32-32-32zm-40 656H184V460h656v380zM184 392V256h128v48c0 4.4 3.6 8 8 8h56c4.4 0 8-3.6 8-8v-48h256v48c0 4.4 3.6 8 8 8h56c4.4 0 8-3.6 8-8v-48h128v136H184z"></path></svg></i>
								23/3/2021
							</div>
							<div class="col-md-2 anticon-eye-number">
								<i aria-label="icon: eye" class="anticon anticon-eye"><svg viewBox="64 64 896 896" focusable="false" class="" data-icon="eye" width="1em" height="1em" fill="currentColor" aria-hidden="true"><path d="M942.2 486.2C847.4 286.5 704.1 186 512 186c-192.2 0-335.4 100.5-430.2 300.3a60.3 60.3 0 0 0 0 51.5C176.6 737.5 319.9 838 512 838c192.2 0 335.4-100.5 430.2-300.3 7.7-16.2 7.7-35 0-51.5zM512 766c-161.3 0-279.4-81.8-362.7-254C232.6 339.8 350.7 258 512 258c161.3 0 279.4 81.8 362.7 254C791.5 684.2 673.4 766 512 766zm-4-430c-97.2 0-176 78.8-176 176s78.8 176 176 176 176-78.8 176-176-78.8-176-176-176zm0 288c-61.9 0-112-50.1-112-112s50.1-112 112-112 112 50.1 112 112-50.1 112-112 112z"></path></svg></i>564
							</div>
						</div>
					</div>
				</div>
				<div class="row right-block">
					<div class="col-md-4" style="background-color: #a4cce6">
						<img src="/assets/css-course.jpg" style="width: 100%; position: absolute; margin: 0px">
					</div>
					<div class="col-md-8">
						<div class="row" style="min-height: 50px; background-color: white">
							<p class="cursor-pointer pt-4 pr-4">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;CSS Advanced</p>
						</div>
						<div class="row block-07" style="min-height: 100px;">
							<div class="col-md-5">
								<span class="ant-tag course-level course-level__advanced">Advanced Level</span>
							</div>
							<div class="col-md-2 mr-2-img">
								<img src="/assets/users.svg" alt="" class="mr-2">120
							</div>
							<div class="col-md-3 anticon anticon-calendar-date">
								<i aria-label="icon: calendar" class="anticon anticon-calendar"><svg viewBox="64 64 896 896" focusable="false" class="" data-icon="calendar" width="1em" height="1em" fill="currentColor" aria-hidden="true"><path d="M880 184H712v-64c0-4.4-3.6-8-8-8h-56c-4.4 0-8 3.6-8 8v64H384v-64c0-4.4-3.6-8-8-8h-56c-4.4 0-8 3.6-8 8v64H144c-17.7 0-32 14.3-32 32v664c0 17.7 14.3 32 32 32h736c17.7 0 32-14.3 32-32V216c0-17.7-14.3-32-32-32zm-40 656H184V460h656v380zM184 392V256h128v48c0 4.4 3.6 8 8 8h56c4.4 0 8-3.6 8-8v-48h256v48c0 4.4 3.6 8 8 8h56c4.4 0 8-3.6 8-8v-48h128v136H184z"></path></svg></i>
								23/3/2021
							</div>
							<div class="col-md-2 anticon-eye-number">
								<i aria-label="icon: eye" class="anticon anticon-eye"><svg viewBox="64 64 896 896" focusable="false" class="" data-icon="eye" width="1em" height="1em" fill="currentColor" aria-hidden="true"><path d="M942.2 486.2C847.4 286.5 704.1 186 512 186c-192.2 0-335.4 100.5-430.2 300.3a60.3 60.3 0 0 0 0 51.5C176.6 737.5 319.9 838 512 838c192.2 0 335.4-100.5 430.2-300.3 7.7-16.2 7.7-35 0-51.5zM512 766c-161.3 0-279.4-81.8-362.7-254C232.6 339.8 350.7 258 512 258c161.3 0 279.4 81.8 362.7 254C791.5 684.2 673.4 766 512 766zm-4-430c-97.2 0-176 78.8-176 176s78.8 176 176 176 176-78.8 176-176-78.8-176-176-176zm0 288c-61.9 0-112-50.1-112-112s50.1-112 112-112 112 50.1 112 112-50.1 112-112 112z"></path></svg></i>564
							</div>
						</div>
					</div>
				</div>

				<div class="row right-block">
					<div class="col-md-4" style="background-color: #a4cce6">
						<img src="/assets/css-course.jpg" style="width: 100%; position: absolute; margin: 0px">
					</div>
					<div class="col-md-8">
						<div class="row" style="min-height: 50px; background-color: white">
							<p class="cursor-pointer pt-4 pr-4">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;CSS Advanced</p>
						</div>
						<div class="row block-07" style="min-height: 100px;">
							<div class="col-md-5">
								<span class="ant-tag course-level course-level__advanced">Advanced Level</span>
							</div>
							<div class="col-md-2 mr-2-img">
								<img src="/assets/users.svg" alt="" class="mr-2">120
							</div>
							<div class="col-md-3 anticon anticon-calendar-date">
								<i aria-label="icon: calendar" class="anticon anticon-calendar"><svg viewBox="64 64 896 896" focusable="false" class="" data-icon="calendar" width="1em" height="1em" fill="currentColor" aria-hidden="true"><path d="M880 184H712v-64c0-4.4-3.6-8-8-8h-56c-4.4 0-8 3.6-8 8v64H384v-64c0-4.4-3.6-8-8-8h-56c-4.4 0-8 3.6-8 8v64H144c-17.7 0-32 14.3-32 32v664c0 17.7 14.3 32 32 32h736c17.7 0 32-14.3 32-32V216c0-17.7-14.3-32-32-32zm-40 656H184V460h656v380zM184 392V256h128v48c0 4.4 3.6 8 8 8h56c4.4 0 8-3.6 8-8v-48h256v48c0 4.4 3.6 8 8 8h56c4.4 0 8-3.6 8-8v-48h128v136H184z"></path></svg></i>
								23/3/2021
							</div>
							<div class="col-md-2 anticon-eye-number">
								<i aria-label="icon: eye" class="anticon anticon-eye"><svg viewBox="64 64 896 896" focusable="false" class="" data-icon="eye" width="1em" height="1em" fill="currentColor" aria-hidden="true"><path d="M942.2 486.2C847.4 286.5 704.1 186 512 186c-192.2 0-335.4 100.5-430.2 300.3a60.3 60.3 0 0 0 0 51.5C176.6 737.5 319.9 838 512 838c192.2 0 335.4-100.5 430.2-300.3 7.7-16.2 7.7-35 0-51.5zM512 766c-161.3 0-279.4-81.8-362.7-254C232.6 339.8 350.7 258 512 258c161.3 0 279.4 81.8 362.7 254C791.5 684.2 673.4 766 512 766zm-4-430c-97.2 0-176 78.8-176 176s78.8 176 176 176 176-78.8 176-176-78.8-176-176-176zm0 288c-61.9 0-112-50.1-112-112s50.1-112 112-112 112 50.1 112 112-50.1 112-112 112z"></path></svg></i>564
							</div>
						</div>
					</div>
				</div>

				
			</div>
		</div>
	</div>
</section>