config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :categories
    resources :questions
    resources :courses
    root 'static_pages#index'
    get 'static_pages/index'
  end
  get 'exam/show'
  resources :courses do
    resources :exams
  end

  devise_for :users,
  path: '',
  path_names: {sign_in: 'login' ,sign_out: 'logout' ,edit: 'profile',sign_up: 'resgistration'},
  controllers: {omniauth_callbacks: 'omniauth_callbacks' }
  # controllers:{omniauth_callbacks: "users/omniauth_callbacks"}
  root 'static_pages#index'

  as :user do
    get "signin" => "devise/sessions#new"
    post "signin" => "devise/sessions#create"
    delete "signout" => "devise/sessions#destroy"
  end


  resources :categories  

  resources :categories
  resources :courses
  resources :exams

  resources :examanswers
  resources :results

  
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    if user.present?  # additional permissions for logged in users (they can see their own exams)
      can :read, Exam, user_id: user.id

      if user.admin?  # additional permissions for administrators
        can :manage, :all
      end
    end
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
	has_many :results
	has_many :exams, through: :results
	belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :courses
	validates :category_name, presence: true
end

app/models/course.rb
class Course < ApplicationRecord
	searchkick
	has_many :exams
	has_many :users, through: :exams
	has_many :objectives
	belongs_to :category
	has_many :questions
	validates :course_name, presence: true
end

app/models/exam.rb
class Exam < ApplicationRecord
	belongs_to :user
	belongs_to :course
	has_many :results


	has_many :questions, through: :results
	has_many :answers, through: :results

	accepts_nested_attributes_for :results
end

app/models/exam_answer.rb
class ExamAnswer < ApplicationRecord
	belongs_to :exam
	belongs_to :answer
end

app/models/exam_question.rb
class ExamQuestion < ApplicationRecord
	belongs_to :exam
	belongs_to :question
end

app/models/objective.rb
class Objective < ApplicationRecord
    belongs_to :course
end

app/models/question.rb
class Question < ApplicationRecord
	searchkick
	has_many :results
	has_many :exams, through: :results
	has_many :answers, dependent: :destroy
	belongs_to :course
	validates :question_name, presence: true
	delegate :course_name, to: :course, prefix: :co, allow_nil: true
	accepts_nested_attributes_for :answers,
	reject_if: proc {|attribute| attribute[:answer_content].blank?}
end

app/models/result.rb
class Result < ApplicationRecord
	belongs_to :exam
	belongs_to :question
	belongs_to :answer, optional: true
	delegate :is_correct, to: :answer, prefix: :answer, allow_nil: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :exams
  has_many :courses, through: :exams
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable,
  :omniauthable , omniauth_providers: [:facebook, :google_oauth2]

  def self.from_omniauth(auth)
  	result = User.where(email: auth.info.email).first
  	if result
  		return result
  	else
  		where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
  			user.email = auth.info.email
  			user.password = Devise.friendly_token[0,20]
  			user.fullname = auth.info.name
  			user.image = auth.info.image
  			user.uid = auth.uid
  			user.provider = auth.provider

        #  If you are using confirmable and the provider(s) you use validate emails
        user.skip_confirmation!
      end
    end
  end
end

app/models/user_course.rb
class UserCourse < ApplicationRecord
	belongs_to :course
	belongs_to :user
end

app/helpers/application_helper.rb
module ApplicationHelper
    include Pagy::Frontend
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/course_helper.rb
module CourseHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/exam_helper.rb
module ExamHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/_footer.html.erb
<footer class="v-layout-footer flex-shrink pb-3 ant-layout-footer">
    <div class="v-layout-footer__content">
        <div class="ant-row">
            <div class="ant-col v-layout-footer-col ant-col-lg-8">
                <h4 class="v-layout-footer-col__head px-4 my-2 font-semibold uppercase">Contact</h4>
                <div class="v-layout-footer-col__main my-4">
                    <ul class="ant-menu v-footer-menu v-footer-menu-socials border-none flex flex-wrap lg:flex-none ant-menu-light ant-menu-root ant-menu-vertical" role="menu">
                        <li class="ant-menu-item m-0 w-1/2 sm:w-1/2 lg:w-full" role="menuitem"><a href="#" class="flex items-center font-medium" target="_blank" rel="noopener noreferrer"><img class="v-footer__menu-icon" alt="email" src="/assets/email.png" /><span><span class="__cf_email__" data-cfemail="4e2d21203a2f2d3a0e38272c2221602f3d272f">Viblo</span></span></a></li>
                        <li class="ant-menu-item m-0 w-1/2 sm:w-1/2 lg:w-full" role="menuitem"><a href="https://facebook.com/viblo-asia" class="flex items-center font-medium" target="_blank" rel="noopener noreferrer"><img class="v-footer__menu-icon" alt="facebook" src="/assets/facebook.png" /><span>Facebook</span></a></li>
                        <li class="ant-menu-item m-0 w-1/2 sm:w-1/2 lg:w-full" role="menuitem"><a href="https://github.com/viblo-asia" class="flex items-center font-medium" target="_blank" rel="noopener noreferrer"><img class="v-footer__menu-icon" alt="github" src="/assets/github.png" /><span>Github</span></a></li>
                        <li class="ant-menu-item m-0 w-1/2 sm:w-1/2 lg:w-full" role="menuitem"><a href="https://viblo.asia/careers" class="flex items-center font-medium" target="_blank" rel="noopener noreferrer"><img class="v-footer__menu-icon" alt="careers" src="/assets/careers.png" /><span>Careers</span></a></li>
                    </ul>
                </div>
            </div>
            <div class="ant-col v-layout-footer-col ant-col-lg-6">
                <h4 class="v-layout-footer-col__head px-4 my-2 font-semibold uppercase">Contents</h4>
                <div class="v-layout-footer-col__main my-4">
                    <ul class="ant-menu v-footer-menu border-none flex flex-wrap lg:flex-none ant-menu-light ant-menu-root ant-menu-vertical" role="menu">
                        <li class="ant-menu-item m-0 w-1/2 sm:w-1/2 lg:w-full" role="menuitem"><a href="/" class="flex items-center font-medium" target="_blank" rel="noopener noreferrer"><span>Home</span></a></li>
                        <li class="ant-menu-item m-0 w-1/2 sm:w-1/2 lg:w-full" role="menuitem"><a href="/courses" class="flex items-center font-medium" target="_blank" rel="noopener noreferrer"><span>Courses</span></a></li>
                        <li class="ant-menu-item m-0 w-1/2 sm:w-1/2 lg:w-full" role="menuitem"><a href="#" class="flex items-center font-medium" target="_blank" rel="noopener noreferrer"><span>Contribute Question</span></a></li>
                        <li class="ant-menu-item m-0 w-1/2 sm:w-1/2 lg:w-full" role="menuitem"><a href="#" class="flex items-center font-medium" target="_blank" rel="noopener noreferrer"><span>Roadmaps</span></a></li>
                    </ul>
                </div>
            </div>
            <div class="ant-col v-layout-footer-col ant-col-lg-5">
                <h4 class="v-layout-footer-col__head px-4 my-2 font-semibold uppercase">Services</h4>
                <div class="v-layout-footer-col__main my-4">
                    <ul class="ant-menu v-footer-menu v-footer-menu-services border-none flex flex-wrap lg:flex-none ant-menu-light ant-menu-root ant-menu-vertical" role="menu">
                        <li class="ant-menu-item m-0 w-1/2 sm:w-1/2 lg:w-full" role="menuitem"><a href="https://viblo.asia" class="flex items-center font-medium" target="_blank" rel="noopener noreferrer"><img class="v-footer__menu-icon" alt="viblo" src="/assets/services/viblo.svg" /><span>Viblo</span></a></li>
                        <li class="ant-menu-item m-0 w-1/2 sm:w-1/2 lg:w-full" role="menuitem"><a href="https://code.viblo.asia" class="flex items-center font-medium" target="_blank" rel="noopener noreferrer"><img class="v-footer__menu-icon" alt="code" src="/assets/services/code.svg" /><span>Viblo Code</span></a></li>
                        <li class="ant-menu-item m-0 w-1/2 sm:w-1/2 lg:w-full" role="menuitem"><a href="https://ctf.viblo.asia" class="flex items-center font-medium" target="_blank" rel="noopener noreferrer"><img class="v-footer__menu-icon" alt="ctf" src="/assets/services/ctf.svg" /><span>Viblo CTF</span></a></li>
                        <li class="ant-menu-item m-0 w-1/2 sm:w-1/2 lg:w-full" role="menuitem"><a href="https://cv.viblo.asia" class="flex items-center font-medium" target="_blank" rel="noopener noreferrer"><img class="v-footer__menu-icon" alt="cv" src="/assets/services/cv.svg" /><span>Viblo CV</span></a></li>
                    </ul>
                </div>
            </div>
            <div class="ant-col v-layout-footer-col ant-col-lg-5">
                <h4 class="v-layout-footer-col__head px-4 my-2 font-semibold uppercase">Terms &amp; Conditions</h4>
                <div class="v-layout-footer-col__main my-4">
                    <ul class="ant-menu v-footer-menu border-none flex flex-wrap lg:flex-none ant-menu-light ant-menu-root ant-menu-vertical" role="menu">
                        <li class="ant-menu-item m-0 w-1/2 sm:w-1/2 lg:w-full" role="menuitem"><a href="#" class="flex items-center font-medium" target="_blank" rel="noopener noreferrer"><span>Support</span></a></li>
                        <li class="ant-menu-item m-0 w-1/2 sm:w-1/2 lg:w-full" role="menuitem"><a href="#" class="flex items-center font-medium" target="_blank" rel="noopener noreferrer"><span>Terms</span></a></li>
                        <li class="ant-menu-item m-0 w-1/2 sm:w-1/2 lg:w-full" role="menuitem"><a class="flex items-center font-medium"><span>Feedback</span></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="v-footer-copyright pt-5 pb-6 flex justify-center">
        <span>
            Copyright©
            <!-- -->2021
            <!-- -->
            <!-- -->Viblo. All rights reserved.
        </span>
    </div>
</footer>
<a class="button-to-top"><img src="/assets/back-to-top.svg" alt="" /></a>

app/views/layouts/_header.html.erb
<div class="vs:hidden xlExtra:block">
    <header class="v-layout-header flex justify-between bg-transparent">
        <div class="v-layout-header__content flex">
            <a class="v-logo-container p-4" href="/"><img class="v-logo" src="/assets/logo.svg" alt="Viblo Learning Logo" /></a>
            <div class="flex flex-row w-full justify-between items-center">
                <div class="v-menu">
                    <ul class="ant-menu ant-menu-light ant-menu-root ant-menu-horizontal" role="menu">
                        <li class="ant-menu-submenu ant-menu-submenu-horizontal ant-menu-overflowed-submenu" style="display:none" role="menuitem">
                            <div class="ant-menu-submenu-title" aria-expanded="false" aria-haspopup="true"><span>···</span><i class="ant-menu-submenu-arrow"></i></div>
                        </li>
                        <li class="ant-menu-item" role="menuitem"><%= link_to "Home", root_path %></li>
                        <li class="ant-menu-submenu ant-menu-submenu-horizontal ant-menu-overflowed-submenu" style="display:none" role="menuitem">
                            <div class="ant-menu-submenu-title" aria-expanded="false" aria-haspopup="true"><span>···</span><i class="ant-menu-submenu-arrow"></i></div>
                        </li>
                        <li class="ant-menu-item" role="menuitem"><%= link_to "Course", courses_path %></li>
                        <li class="ant-menu-submenu ant-menu-submenu-horizontal ant-menu-overflowed-submenu" style="display:none" role="menuitem">
                            <div class="ant-menu-submenu-title" aria-expanded="false" aria-haspopup="true"><span>···</span><i class="ant-menu-submenu-arrow"></i></div>
                        </li>
                    </ul>
                </div>
                <div class="flex flex-row items-center">
                    <div class="v-searchbox mr-8">
                        <span class="ant-input-search ant-input-affix-wrapper">
                        <form action="/courses" id="course-search-form">
                                <input type="text" name="course" placeholder="What do you want to learn?" value="" class="ant-input">
                                <span class="ant-input-suffix" onclick="document.querySelector('#course-search-form').submit()">
                                    <i aria-label="icon: search" tabindex="-1" class="anticon anticon-search ant-input-search-icon">
                                        <svg viewBox="64 64 896 896" focusable="false" class="" data-icon="search" width="1em" height="1em" fill="currentColor" aria-hidden="true">
                                            <path d="M909.6 854.5L649.9 594.8C690.2 542.7 712 479 712 412c0-80.2-31.3-155.4-87.9-212.1-56.6-56.7-132-87.9-212.1-87.9s-155.5 31.3-212.1 87.9C143.2 256.5 112 331.8 112 412c0 80.1 31.3 155.5 87.9 212.1C256.5 680.8 331.8 712 412 712c67 0 130.6-21.8 182.7-62l259.7 259.6a8.2 8.2 0 0 0 11.6 0l43.6-43.5a8.2 8.2 0 0 0 0-11.6zM570.4 570.4C528 612.7 471.8 636 412 636s-116-23.3-158.4-65.6C211.3 528 188 471.8 188 412s23.3-116.1 65.6-158.4C296 211.3 352.2 188 412 188s116.1 23.2 158.4 65.6S636 352.2 636 412s-23.3 116.1-65.6 158.4z"></path>
                                        </svg>
                                    </i>
                                </span>
                        </form>
                        </span>
                    </div>
                    <% if current_user %>
                    <div class="flex ant-dropdown-trigger dropdown">
                        <span role="img" aria-label="caret-down" class="anticon anticon-caret-down flex items-center cursor-pointer" data-toggle="dropdown"><svg viewBox="0 0 1024 1024" focusable="false" class="" data-icon="caret-down" width="1em" height="1em" fill="currentColor" aria-hidden="true"><path d="M840.4 300H183.6c-19.7 0-30.7 20.8-18.5 35l328.4 380.8c9.4 10.9 27.5 10.9 37 0L858.9 335c12.2-14.2 1.2-35-18.5-35z"></path></svg></span>
                        <span class="name flex items-center cursor-pointer" data-toggle="dropdown">chiennt</span>
                        <div class="flex items-center border-avatar" data-toggle="dropdown"><img class="v-avatar cursor-pointer" src="https://images.viblo.asia/60/03d3db71-0e38-4090-8d36-5a293591764e.png" srcset="https://images.viblo.asia/120/03d3db71-0e38-4090-8d36-5a293591764e.png 2x" alt="chiennt" style="width: 60px; height: 60px;"></div>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                          <%= link_to "Enrolled Courses", '#', class: "dropdown-item" %>
                          <%= link_to "Tests", exams_path, class: "dropdown-item" %>
                          <%= link_to "Profile", edit_user_registration_path, class: "dropdown-item" %>
                          <div class="dropdown-divider"></div>
                          <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
                        </div>
                    </div>
                    <% else %>
                    <div>
                        <%= link_to "Sign In", new_user_session_path, class: "btn-login font-bold mr-5" %>
                        <button class="capitalize v-button v-button-primary v-button-large"><%= link_to "Register", new_user_registration_path %></button>
                    </div>
                    <% end %>

                </div>
            </div>
        </div>
    </header>
</div>
<div class="sm-header vs:block xlExtra:hidden">
    <div class="sm-header__header">
        <div class="sm-header__top">
            <div class="sm-header__top__logo"><a class="v-logo-container " href="/"><img class="v-logo" src="/assets/logo.svg" alt="Viblo Learning Logo" /></a></div>
            <div class="sm-header__top__btn-nav sm-header__top__btn-nav--left">
                <div class="flex flex-row w-full justify-between">
                <div class="v-menu">
                    <ul class="ant-menu ant-menu-light ant-menu-root ant-menu-horizontal" role="menu">
                        <li class="ant-menu-submenu ant-menu-submenu-horizontal ant-menu-overflowed-submenu" style="display:none" role="menuitem">
                            <div class="ant-menu-submenu-title" aria-expanded="false" aria-haspopup="true"><span>···</span><i class="ant-menu-submenu-arrow"></i></div>
                        </li>
                        <li class="ant-menu-item" role="menuitem"><%= link_to "Home", root_path %></li>
                        <li class="ant-menu-submenu ant-menu-submenu-horizontal ant-menu-overflowed-submenu" style="display:none" role="menuitem">
                            <div class="ant-menu-submenu-title" aria-expanded="false" aria-haspopup="true"><span>···</span><i class="ant-menu-submenu-arrow"></i></div>
                        </li>
                        <li class="ant-menu-item" role="menuitem"><%= link_to "Course", courses_path %></li>
                        <li class="ant-menu-submenu ant-menu-submenu-horizontal ant-menu-overflowed-submenu" style="display:none" role="menuitem">
                            <div class="ant-menu-submenu-title" aria-expanded="false" aria-haspopup="true"><span>···</span><i class="ant-menu-submenu-arrow"></i></div>
                        </li>
                        <li class="ant-menu-item" role="menuitem">
                            <form action="/courses">
                                    <input type="text" name="course" placeholder="What do you want to learn?" value="" class="ant-input">
                                    <span class="ant-input-suffix">
                                        <i aria-label="icon: search" tabindex="-1" class="anticon anticon-search ant-input-search-icon">
                                            <svg viewBox="64 64 896 896" focusable="false" class="" data-icon="search" width="1em" height="1em" fill="currentColor" aria-hidden="true">
                                                <path d="M909.6 854.5L649.9 594.8C690.2 542.7 712 479 712 412c0-80.2-31.3-155.4-87.9-212.1-56.6-56.7-132-87.9-212.1-87.9s-155.5 31.3-212.1 87.9C143.2 256.5 112 331.8 112 412c0 80.1 31.3 155.5 87.9 212.1C256.5 680.8 331.8 712 412 712c67 0 130.6-21.8 182.7-62l259.7 259.6a8.2 8.2 0 0 0 11.6 0l43.6-43.5a8.2 8.2 0 0 0 0-11.6zM570.4 570.4C528 612.7 471.8 636 412 636s-116-23.3-158.4-65.6C211.3 528 188 471.8 188 412s23.3-116.1 65.6-158.4C296 211.3 352.2 188 412 188s116.1 23.2 158.4 65.6S636 352.2 636 412s-23.3 116.1-65.6 158.4z"></path>
                                            </svg>
                                        </i>
                                    </span>
                            </form>
                        </li>
                    </ul>
                </div>
                <div class="flex flex-row items-center">
                    <% if current_user %>
                    <div class="flex ant-dropdown-trigger dropdown">
                        <span role="img" aria-label="caret-down" class="anticon anticon-caret-down flex items-center cursor-pointer" data-toggle="dropdown"><svg viewBox="0 0 1024 1024" focusable="false" class="" data-icon="caret-down" width="1em" height="1em" fill="currentColor" aria-hidden="true"><path d="M840.4 300H183.6c-19.7 0-30.7 20.8-18.5 35l328.4 380.8c9.4 10.9 27.5 10.9 37 0L858.9 335c12.2-14.2 1.2-35-18.5-35z"></path></svg></span>
                        <span class="name flex items-center cursor-pointer" data-toggle="dropdown">chiennt</span>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                          <%= link_to "Enrolled Courses", '#', class: "dropdown-item" %>
                          <%= link_to "Tests", exams_path, class: "dropdown-item" %>
                          <%= link_to "Profile", edit_user_registration_path, class: "dropdown-item" %>
                          <div class="dropdown-divider"></div>
                          <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
                        </div>
                    </div>
                    <% else %>
                    <div class="flex">
                        <%= link_to "Sign In", new_user_session_path, class: "capitalize v-button v-button-small" %>
                        <%= link_to "Register", new_user_registration_path, class: "capitalize v-button v-button-primary v-button-small" %>
                    </div>
                    <% end %>
                </div>
            </div>
            </div>
        </div>
    </div>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>

<head>
    <title><%= yield(:title) + ' | Admin' %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag asset_path('logo.png') %>
</head>

<body>
    <%= render 'layouts/admin/nav' %>
    <div class="container-fluid">
        <div class="row">
            <%= render 'layouts/admin/sidebar'%>
            <main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
                <%= yield %>
            </main>
        </div>
    </div>
</body>

</html>

app/views/layouts/admin/_nav.html.erb
<nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0">
    <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="#">PR2010F-FELS</a>
    <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
    <ul class="navbar-nav px-3">
        <li class="nav-item text-nowrap">
            <a class="nav-link" href="#">Sign out</a>
        </li>
    </ul>
</nav>

app/views/layouts/admin/_sidebar.html.erb
<nav class="col-md-2 d-none d-md-block bg-light sidebar">
    <div class="sidebar-sticky">
        <ul class="nav flex-column">
            <li class="nav-item">

                <%= link_to (admin_static_pages_index_path), class: "nav-link" do%>
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-home">
                    <path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path>
                    <polyline points="9 22 9 12 15 12 15 22"></polyline>
                </svg>
                Home
                <% end %>
            </li>

            <li class="nav-item">
                <%= link_to (admin_questions_path), class: "nav-link" do%>
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-file">
                    <path d="M13 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V9z"></path>
                    <polyline points="13 2 13 9 20 9"></polyline>
                </svg>
                Questions
                <% end %>
            </li>

            <li class="nav-item">
                <%= link_to (admin_categories_path), class: "nav-link" do%>
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-layers">
                    <polygon points="12 2 2 7 12 12 22 7 12 2"></polygon>
                    <polyline points="2 17 12 22 22 17"></polyline>
                    <polyline points="2 12 12 17 22 12"></polyline>
                </svg>
                Categories
                <% end %>
            </li>


                <a class="nav-link active" href="#">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-home">
                        <path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path>
                        <polyline points="9 22 9 12 15 12 15 22"></polyline>
                    </svg>
                    Dashboard <span class="sr-only">(current)</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-file">
                        <path d="M13 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V9z"></path>
                        <polyline points="13 2 13 9 20 9"></polyline>
                    </svg>
                    Orders
                </a>
            </li>

            <li class="nav-item">
                <%= link_to (admin_courses_path), class: "nav-link" do%>
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-file-text">
                    <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path>
                    <polyline points="14 2 14 8 20 8"></polyline>
                    <line x1="16" y1="13" x2="8" y2="13"></line>
                    <line x1="16" y1="17" x2="8" y2="17"></line>
                    <polyline points="10 9 9 9 8 9"></polyline>
                </svg>
                Courses
                <% end %>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="#">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-users">
                        <path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path>
                        <circle cx="9" cy="7" r="4"></circle>
                        <path d="M23 21v-2a4 4 0 0 0-3-3.87"></path>
                        <path d="M16 3.13a4 4 0 0 1 0 7.75"></path>
                    </svg>
                    Users
                </a>
            </li>
        </ul>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title><%= yield(:title) %></title>
  
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>


  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= favicon_link_tag asset_path('logo.png') %>
</head>

<body>
  <%= render 'layouts/header' %>
  <%= yield %>
  <div class="container-fluid">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </div>
  <%= render 'layouts/footer' %>
</body>

</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
<div id="error_explanation">
    <h2>The form contains <%= pluralize(object.errors.count, "error") %></h2>
    <ul>
        <% object.errors.each do |error| %>
        <li><%= error.full_messages %></li>
        <% end %>
    </ul>
</div>
<% end %>